/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Ignore;
import org.junit.Test;

public class LibraryTest {
    @Test
    @Ignore
    public void clienteCompraCocaPor120MangosHabiendoCostado10ManosResultandoUnaGanaciaDe110() {

    }

    @Test
    @Ignore
    public void clienteCompraCocaPor120MangosHabiendoCostado10ManosResultandoUnaGanaciaNoEsDe110() {
    }

    @Test
    @Ignore
    public void clienteCompraPapasPor200MangosHabiendoCostado5ManosResultandoUnaGanaciaDe195() {

    }

    @Test
    @Ignore
    public void clienteCompraComboPapasCocaPor1000MangosHabiendoCostado5laPapa10laCocaResultandoUnaGanaciaDe985() {
    }

    @Test
    @Ignore
    public void clienteCompraCocaPor100MangosHabiendoCompradoPackDe6Por6ResultandoUnaGanaciaDe99() {
    }

    @Test
    @Ignore
    public void clienteCompraComboDeCocaCervezaManiHabiendoCompradoUnPackDeCocaUnPackDeCervezaUnManiResultandoUNaGanancia() {
    }


              /*
    @Test
    public void testUnChinitoCompraUnaSpriteA12pYLaVendeA150pLaRentaEsDe138p(){
        Sprite sprite = new Sprite(12);

        Venta venta = new Venta(sprite, 150);

        assertEquals(138, venta.rentabilidad());
    }

    @Test
    public void testUnChinitoCompraUnaSpriteA10pYLaVendeA150pLaRentaEsDe140p(){
        Sprite sprite = new Sprite(10);

        Venta venta = new Venta(sprite, 150);

        assertEquals(140, venta.rentabilidad());

    }

    @Test
    public void testUnChinitoCompraUnaFritaA30pYLaVendeA40pLaRentaEsDe10p(){
        Papa papa = new Papa(30);

        Venta venta = new Venta(papa, 40);

        assertEquals(10, venta.rentabilidad());
    }

    @Test public void testUnChinitoCompraUnPackDe10Coca600pVendeUnaCocaa150p(){
        Paquete pack = new Paquete( new Coca(), 10, 600);

        Venta venta = new Venta(pack.unidad(), 150);

        assertEquals(90, venta.rentabilidad());
    }

    @Test public void testUnChinitoCompraUnPackDe10Papa600pVendeUnaPapaa150p(){
        Paquete pack = new Paquete( new Papa(), 10, 600);

        Venta venta = new Venta(pack.unidad(), 150);

        assertEquals(90, venta.rentabilidad());
    }

     */
}
