/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Ignore;
import org.junit.Test;

public class LibraryTest {
    @Test
    @Ignore
    public void clienteCompraCocaPor120MangosHabiendoCostado10ManosResultandoUnaGanaciaDe110() {

    }

    @Test
    @Ignore
    public void clienteCompraCocaPor120MangosHabiendoCostado10ManosResultandoUnaGanaciaNoEsDe110() {
    }

    @Test
    @Ignore
    public void clienteCompraPapasPor200MangosHabiendoCostado5ManosResultandoUnaGanaciaDe195() {

    }

    @Test
    @Ignore
    public void clienteCompraComboPapasCocaPor1000MangosHabiendoCostado5laPapa10laCocaResultandoUnaGanaciaDe985() {
    }

    @Test
    @Ignore
    public void clienteCompraCocaPor100MangosHabiendoCompradoPackDe6Por6ResultandoUnaGanaciaDe99() {
    }

    @Test
    @Ignore
    public void clienteCompraComboDeCocaCervezaManiHabiendoCompradoUnPackDeCocaUnPackDeCervezaUnManiResultandoUNaGanancia() {
    }


}
